flavour: charm # charm, beauty, charmbeauty
nevents: 10000000
seed: 0
collenergy: 5020 # GeV

selections:
    rapidity: [-10., 10.]
    pt: [0., 1.e+10]

tunes:
    tune: 14 # 4=2M, 5=4C, 6=4Cx, 14=Monash
    process: SoftQCD # alternatives: HardQCDCharm, HardQCDBeauty, HardQCDCharmBeauty
    paperSkandsMode: 3
    advanced: # custom non-standard configurations (enabled only if paperSkandsMode == -1)
        CRmode: -1
        qq1toQQ0charm: 0
        qq1toQQ0beauty: 0
        timeDilationMode: 0
        doSigmaLoop: 0
        doubleJunct: 1
        m0: -1

output:
    filename: CharmHadrons_pp5dot02TeV_Pythia8_SoftQCD_CRmode3.root